### ISSUE TITLE
Question about "We query the SAM backbone feature extractor once per image."

### ISSUE THREAD

**Issue by zhenshan0127** [makezur/super_primitive#1]
Hello,

Thanks for this amazing work. I am confused about this sentence, "**We query the SAM backbone feature extractor once per image.**", at the section, **Image Segment Retrieval**. Because you mentiond twice random sampled points later (300 points and 100 points).

Could you pleae give me more explanation about it and how is it reflected in the code?

Regards,
Zhenshan

**Comment by makezur** [comment]
Hi Zhenshan,

This implementation slightly differs from the CVPR one. Here, the SAM implementation details are abstracted away, as other, more efficient versions may operate differently. You can easily achieve the original behaviour by moving the feature extraction stage https://github.com/makezur/super_primitive/blob/37e7d7685ceba533a3fdda47c191bddc4d7dd698/frontend/segment/sam_tools.py#L26 into the `infer_masks` function.

Feel free to reach me out if you have any other questions,
Kirill
