### ISSUE TITLE
Questions about depth completion results.

### ISSUE THREAD

**Issue by zhenshan0127** [makezur/super_primitive#2]
Hello,

Thanks for the excellent performance in depth completion. But I notice that there are some outlier points existing in the 3D reconstructions as shown below. What's the reason for this?

![image](https://github.com/makezur/super_primitive/assets/16939852/8a4f7c70-0974-4978-8a4c-1283166e39d9)

Thanks for your time and patience.

Regard,
Zhenshan

**Comment by makezur** [comment]
Hi Zhenshan,

That type of noise typically comes from imperfect segmentation and its misalignment with estimated surface normals. Most of the time, it works just fine. However, if misalignment occurs, the result of the surface normal integration might appear a bit noisy.

Let me know if you have any further questions!

Best,
Kirill

**Comment by zhenshan0127** [comment]
Hello Kirill,

Thanks for your reply.

Regards,
Zhenshan
